-- ✅ 유저 테이블
CREATE TABLE USERS (
    USER_NUM INT AUTO_INCREMENT PRIMARY KEY COMMENT '유저 번호',
    USER_ID VARCHAR(100) NOT NULL COMMENT '유저 아이디',
    USER_NAME VARCHAR(100) NOT NULL COMMENT '유저 이름',
    USER_AGE INT CHECK (USER_AGE >= 0) COMMENT '유저 나이',
    FAMILY_HISTORY VARCHAR(255) COMMENT '가족력',
    ALLERGY JSON COMMENT '보유 알러지 (보유 여부 및 종류 JSON)',
    COIN INT DEFAULT 0 CHECK (COIN >= 0) COMMENT '보유 코인',
    INS_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    UPD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='유저';

-- ✅ 채팅 로그 테이블
CREATE TABLE CHAT_LOG (
    CHAT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '채팅 번호',
    MESSAGE TEXT COMMENT '채팅 내용',
    SENDER_TYPE ENUM('USER', 'AI') COMMENT '채팅 유형',
    SENT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '채팅 발송일',
    USER_NUM INT NOT NULL COMMENT '유저 번호',
    FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='채팅 로그';

-- ✅ 캐시 데이터 테이블 (JSON 저장용)
CREATE TABLE DIET_DATA (
    DATA_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '데이터 번호',
    DISEASE_NAME VARCHAR(255) UNIQUE NOT NULL COMMENT '질병명',
    DATA_JSON JSON NOT NULL COMMENT '내부 데이터/AI 캐시',
    INS_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    UPD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='캐시 테이블';

-- ✅ 결제 테이블
CREATE TABLE PAYMENT (
    PAY_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '결제 번호',
    PAY_AMOUNT DECIMAL(10, 2) NOT NULL CHECK (PAY_AMOUNT > 0) COMMENT '결제 금액',
    PAY_METHOD VARCHAR(50) COMMENT '결제 종류',
    COIN_AMOUNT INT NOT NULL CHECK (COIN_AMOUNT > 0) COMMENT '결제 코인',
    PAY_STATUS ENUM('SUCCESS', 'FAILED', 'PENDING') DEFAULT 'SUCCESS' COMMENT '결제 상태',
    PAY_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '결제일',
    USER_NUM INT NOT NULL COMMENT '유저 번호',
    FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='결제';

-- ✅ 환불 테이블
CREATE TABLE REFUND (
    REF_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '환불 번호',
    REF_AMOUNT DECIMAL(10, 2) NOT NULL CHECK (REF_AMOUNT > 0) COMMENT '환불 금액',
    REF_REASON VARCHAR(255) COMMENT '환불 사유',
    REF_STATUS ENUM('REQUESTED', 'APPROVED', 'DENIED') DEFAULT 'REQUESTED' COMMENT '환불 상태',
    REF_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '환불일',
    USER_NUM INT NOT NULL COMMENT '유저 번호',
    PAY_ID INT NOT NULL COMMENT '결제 번호',
    FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    FOREIGN KEY (PAY_ID) REFERENCES PAYMENT(PAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='환불';
